# Generated by Django 2.1.4 on 2018-12-25 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
