# Generated by Django 2.1.4 on 2018-12-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0002_auto_20181221_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='hot_pric',
            field=models.DecimalField(decimal_places=2, default=99.99, max_digits=7),
        ),
    ]
