# Generated by Django 2.1.4 on 2018-12-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0005_auto_20181221_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='hot_pric',
            new_name='hot_price',
        ),
        migrations.AddField(
            model_name='book',
            name='isdelete',
            field=models.BooleanField(default=False),
        ),
    ]
