# Generated by Django 2.1.4 on 2018-12-22 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodel', '0006_auto_20181222_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nulltest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr1', models.CharField(max_length=20, verbose_name='字段1')),
                ('attr2', models.CharField(max_length=20, null=True, verbose_name='字段2')),
                ('attr3', models.CharField(blank=True, max_length=20, null=True, verbose_name='字段3')),
            ],
        ),
    ]
