# Generated by Django 2.1.4 on 2018-12-25 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_title', models.CharField(max_length=30)),
                ('a_brief', models.CharField(blank=True, max_length=150, null=True)),
                ('ar_content', models.CharField(max_length=10240)),
                ('ar_create_time', models.DateTimeField(auto_now=True)),
                ('ar_update_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comm_text', models.CharField(max_length=300)),
                ('comm_time', models.DateTimeField(auto_now=True)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boke1225.Article')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_name', models.CharField(max_length=20)),
                ('us_pswd', models.CharField(max_length=128)),
                ('us_register_time', models.DateTimeField(auto_now=True)),
                ('us_nickname', models.CharField(max_length=20)),
                ('us_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boke1225.UserInfo'),
        ),
        migrations.AddField(
            model_name='article',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boke1225.UserInfo'),
        ),
    ]
