# Generated by Django 2.1.4 on 2018-12-25 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boke1225', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='a_brief',
            new_name='ar_brief',
        ),
    ]
